# Menu
menu:
  首页: /
  归档: /archives
  相册: /gallery
  收藏: /favorites
  关于: /about
rss: /atom.xml

# Miscellaneous
# favicon: /favicon.ico
favicon: /study.svg
brand: /images/shark.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/shark-inverted.svg

# Content
excerpt_link: 阅读全文...

# MIIT ICP/IP/DOMAIN
beian:
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: true
  clientID: 5c428a36d9a70c430942
  clientSecret: 3b4c82d3877613930437eeade7101706d718c5d8
  repo: gitalk
  owner: Augenestern
  admin: Augenestern

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'

#爱心点击
lovejs: true

post_wordcount:
  item_text: true
  wordcount: true
  min2read: true
  totalcount: true
  separated_meta: true

